### ISSUE TITLE
Getting ClassNotFoundException for spi.Plugin

### ISSUE THREAD

**Issue by agupta94** [rchukh/presto-querylog#6]
Hi! I followed all the steps provided in the README, but I am getting the following error -

`2019-07-30T22:10:02.296Z	ERROR	main	com.facebook.presto.server.PrestoServer	io/prestosql/spi/Plugin
java.lang.NoClassDefFoundError: io/prestosql/spi/Plugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:80)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:273)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:234)
	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:164)
	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:156)
	at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:137)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:117)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
Caused by: java.lang.ClassNotFoundException: io.prestosql.spi.Plugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:80)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more`

Any help would be appreciated. Thanks!

**Comment by rchukh** [comment]
Hi. Thanks for reporting this.
After migrating from PrestoDB to PrestoSQL I've missed that the Service Loader filename should also be changed.
It is fixed now (running and logging on the 316 version locally) and will be in master in a minute.

I've raised the #8 to implement some end-to-end integration tests in the future.

**Comment by agupta94** [comment]
Hi! Thanks for responding quickly and fixing the problem! I am getting the following error now -
`2019-07-31T15:47:40.109Z	ERROR	main	com.facebook.presto.server.PrestoServer	Event listener presto-querylog is not registered
java.lang.IllegalStateException: Event listener presto-querylog is not registered
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at com.facebook.presto.eventlistener.EventListenerManager.setConfiguredEventListener(EventListenerManager.java:81)
	at com.facebook.presto.eventlistener.EventListenerManager.loadConfiguredEventListener(EventListenerManager.java:68)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:144)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:73)`

Could you please help me with this? Thanks!
